services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        environment: 
            - EMAIL_HOST_USER=campaabraham@gmail.com
        volumes:     
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: postgres:13
        volumes: 
           - postgres_data:/var/lib/postgresql/data
        environment: 
            POSTGRES_DB: "db"
            POSTGRES_PASSWORD: postgres
            PASSWORD_USSER: postgres
            POSTGRES_HOST_AUTH_METHOD: "trust"
        ports:
            - 5432:5432
volumes:
    postgres_data:

      
